#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "cloud_disk_service.pb.h"

namespace cloud_disk_service
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void signup(signup_request *request, signup_response *response,
					srpc::RPCContext *ctx) = 0;

	virtual void signin(signin_request *request, signin_response *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using signupDone = std::function<void (signup_response *, srpc::RPCContext *)>;
using signinDone = std::function<void (signin_response *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void signup(const signup_request *req, signupDone done);
	void signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> async_signup(const signup_request *req);

	void signin(const signin_request *req, signinDone done);
	void signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> async_signin(const signin_request *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_signup_task(signupDone done);
	srpc::SRPCClientTask *create_signin_task(signinDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void signup(const signup_request *req, signupDone done);
	void signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> async_signup(const signup_request *req);

	void signin(const signin_request *req, signinDone done);
	void signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> async_signin(const signin_request *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_signup_task(signupDone done);
	srpc::SRPCHttpClientTask *create_signin_task(signinDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void signup(const signup_request *req, signupDone done);
	void signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> async_signup(const signup_request *req);

	void signin(const signin_request *req, signinDone done);
	void signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> async_signin(const signin_request *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_signup_task(signupDone done);
	srpc::BRPCClientTask *create_signin_task(signinDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void signup(const signup_request *req, signupDone done);
	void signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> async_signup(const signup_request *req);

	void signin(const signin_request *req, signinDone done);
	void signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> async_signin(const signin_request *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_signup_task(signupDone done);
	srpc::TRPCClientTask *create_signin_task(signinDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void signup(const signup_request *req, signupDone done);
	void signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> async_signup(const signup_request *req);

	void signin(const signin_request *req, signinDone done);
	void signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> async_signin(const signin_request *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_signup_task(signupDone done);
	srpc::TRPCHttpClientTask *create_signin_task(signinDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("cloud_disk_service")
{
	this->srpc::RPCService::add_method("signup",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::signup);
		});

	this->srpc::RPCService::add_method("signin",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::signin);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("cloud_disk_service")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("cloud_disk_service")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::signup(const signup_request *req, signupDone done)
{
	auto *task = this->create_rpc_client_task("signup", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> SRPCClient::async_signup(const signup_request *req)
{
	using RESULT = std::pair<signup_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signup_response>("signup", srpc::RPCAsyncFutureCallback<signup_response>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::signin(const signin_request *req, signinDone done)
{
	auto *task = this->create_rpc_client_task("signin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> SRPCClient::async_signin(const signin_request *req)
{
	using RESULT = std::pair<signin_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signin_response>("signin", srpc::RPCAsyncFutureCallback<signin_response>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_signup_task(signupDone done)
{
	return this->create_rpc_client_task("signup", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_signin_task(signinDone done)
{
	return this->create_rpc_client_task("signin", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("cloud_disk_service")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("cloud_disk_service")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::signup(const signup_request *req, signupDone done)
{
	auto *task = this->create_rpc_client_task("signup", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> SRPCHttpClient::async_signup(const signup_request *req)
{
	using RESULT = std::pair<signup_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signup_response>("signup", srpc::RPCAsyncFutureCallback<signup_response>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::signin(const signin_request *req, signinDone done)
{
	auto *task = this->create_rpc_client_task("signin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> SRPCHttpClient::async_signin(const signin_request *req)
{
	using RESULT = std::pair<signin_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signin_response>("signin", srpc::RPCAsyncFutureCallback<signin_response>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_signup_task(signupDone done)
{
	return this->create_rpc_client_task("signup", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_signin_task(signinDone done)
{
	return this->create_rpc_client_task("signin", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("cloud_disk_service")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("cloud_disk_service")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::signup(const signup_request *req, signupDone done)
{
	auto *task = this->create_rpc_client_task("signup", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> BRPCClient::async_signup(const signup_request *req)
{
	using RESULT = std::pair<signup_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signup_response>("signup", srpc::RPCAsyncFutureCallback<signup_response>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::signin(const signin_request *req, signinDone done)
{
	auto *task = this->create_rpc_client_task("signin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> BRPCClient::async_signin(const signin_request *req)
{
	using RESULT = std::pair<signin_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signin_response>("signin", srpc::RPCAsyncFutureCallback<signin_response>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_signup_task(signupDone done)
{
	return this->create_rpc_client_task("signup", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_signin_task(signinDone done)
{
	return this->create_rpc_client_task("signin", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("cloud_disk_service")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("cloud_disk_service")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::signup(const signup_request *req, signupDone done)
{
	auto *task = this->create_rpc_client_task("/cloud_disk_service/signup", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> TRPCClient::async_signup(const signup_request *req)
{
	using RESULT = std::pair<signup_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signup_response>("/cloud_disk_service/signup", srpc::RPCAsyncFutureCallback<signup_response>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::signin(const signin_request *req, signinDone done)
{
	auto *task = this->create_rpc_client_task("/cloud_disk_service/signin", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> TRPCClient::async_signin(const signin_request *req)
{
	using RESULT = std::pair<signin_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signin_response>("/cloud_disk_service/signin", srpc::RPCAsyncFutureCallback<signin_response>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_signup_task(signupDone done)
{
	auto *task = this->create_rpc_client_task("/cloud_disk_service/signup", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_signin_task(signinDone done)
{
	auto *task = this->create_rpc_client_task("/cloud_disk_service/signin", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("cloud_disk_service")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("cloud_disk_service")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::signup(const signup_request *req, signupDone done)
{
	auto *task = this->create_rpc_client_task("signup", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::signup(const signup_request *req, signup_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signup_response, srpc::RPCSyncContext>> TRPCHttpClient::async_signup(const signup_request *req)
{
	using RESULT = std::pair<signup_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signup_response>("signup", srpc::RPCAsyncFutureCallback<signup_response>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::signin(const signin_request *req, signinDone done)
{
	auto *task = this->create_rpc_client_task("signin", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::signin(const signin_request *req, signin_response *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<signin_response, srpc::RPCSyncContext>> TRPCHttpClient::async_signin(const signin_request *req)
{
	using RESULT = std::pair<signin_response, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<signin_response>("signin", srpc::RPCAsyncFutureCallback<signin_response>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_signup_task(signupDone done)
{
	auto *task = this->create_rpc_client_task("signup", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_signin_task(signinDone done)
{
	auto *task = this->create_rpc_client_task("signin", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace cloud_disk_service

